## Main config
engines:
  tslint:
    enabled: true
    channel: beta
  scss-lint:
    enabled: true
  eslint:
    enabled: false
  csslint:
    enabled: false

ratings:
  paths:
  - "**.scss"
  - "**.ts"

## other configuration excluded from example...
exclude_paths:
- ".vscode/"
- "documentation/"
- "dist/prism.css"
- "dist/prism.js"
- "extensions/"
- "sample/"
- "tests/"
- "tools/"
- "vendors/"