language: node_js
node_js:
- '6'
before_script:
- npm install
script: npm run build
notifications:
  slack:
    matrix:
    - babylonjs:pNQ3IVQnPxQwFNVOdiq9M4N3
    rooms:
      secure: vrovc+72GN4baF5kEKfE8OkZmeqDLO3EY2hwshaFS+u3uZilTTz1QbDDIpHhY0S8/g/3C66m/KDhsGDIZLY3xVVvRU5w3iego/tIwoxzp/JM/1380CfOK0KBYt1Mor2XwE5ZCp1rBMfEVkckYZhHT13jHyOWymWbU+e91w0KD4ovM3+hKix9tl//Ia57LriPyltRXZNDBo5t7tq6IE5yINeg8hqwbHyXcXVCnbvuFjKmkw7AehYgSR2xU3Axj8SaZzqlCG6XwEwZIEkVr98vDc5wlSeP1fF56VmyZ1hUbViH4wimN2TmZsgZiAi6yjSh9Zjo9HnQD290ij/XdIXCp9fB5Am7GF41Y5f4O4pbeoUWxcxOCD4Lpr5T3HUlxuS1gx5XWJJ409kdZwpV/r7/lf4NnX+3iY80zFjbDix5nBwZSiMt2cuM+n7LlJHJXONNhzGwJ9fACpAbQ5Wvl2VjgoQ1sxUQmCnPxjpcG+G0eeZOmv6BDK9L2mkCZJwoa9ESfmg4OL2vcEoMvlSI0ruTtA8A54W2cTXhPY7OQgWJSx1nGE7MNbgsYEBsFOtSyYBwdg5ZHyz7D/t1VASdcM6s5PvTfsWsJGZAPFHqsIgMaBHu8H1xKmfJLWJref6XBrKmOvTzKHY2GYVeT3c9tSrgcsOfzjWfs3GZVCQDoFv8MaE=
